### ISSUE TITLE
The queue is completly broken

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#18] opened 2014-03-06 10:45 UTC
Makes both players 1 or not working at all. 

@FireyFly 
@Zetro

**Comment by FireyFly** [comment] 2014-03-06 17:47
No, the queue currently allows a player to enter the queue even when they have been assigned as a player. This is apparently the wrong behaviour, so I'll change that; since I was unsure I opted to not alter the existing behaviour earlier.

If Alice presses "join queue", then Bob presses "join queue", all things should work just fine. If Alice presses "join queue" twice, she'll take both positions. (I'm almost considering closing as invalid & opening a new issue, but I'm not sure if I could be bothered... for future issues, I think it's a good idea to be more precise and ideally add steps to reproduce the bug if it's reproducible.)

**Comment by hleskela** [comment] 2014-03-20 22:32
Could not get the queue to work properly, same issues as wamanuz. If Alice, my iPhone joined the queue, she was player one. If Bob, my pc, joined the queue, he became a spectator, number one in queue. If Alice then played, her move would be registered and Bob would now join the game as player one as well. Alice now has to wait for the other player, but if Bob makes a move, nothing changes for Alice and now Bob also waits for the other player. Thus they are stuck.

Edit*
Changed my mind, it seems to work... at least sometimes. Brb, testing for bugs.

Edit 2*
Retracted everything, go Jonas, go!

**Comment by Zetro** [comment] 2014-03-23 14:27
Can't reproduce this and clients won't be able to queue multiple times anymore due to feacb7f9bdaef6404fe41bb4ef82396600e7579d.

**Closed as completed by Zetro** 2014-03-23 14:27 UTC
Labels: games
