### ISSUE TITLE
[queue,games] Queue is completly broken 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#92] opened 2014-05-05 12:29 UTC
When enqueuing a 4th client (after player 1, player 2, queuepos 1) the third client is kicked from the queue and the 4th player takes it's place.

**Comment by Zetro** [comment] 2014-05-06 14:31
Intended behavior (assuming this was tested in the same browser instance).

What probably happens:
- 1st client connects and receives a session key/id 0cf1, joins the queue identifying with key 0cf1 and becomes player 1. (queue: empty)
- 2nd client connects and already has a session (0cf1), joins the queue with key 0cf1 and becomes player 2. (queue: empty)
- 3rd client connects and already has a session (0cf1), joins the queue with key 0cf1 and is placed first in the queue. (queue: 0cf1=3rd)
- 4th client connects and already has a session (0cf1), joins the queue with key 0cf1 but the another client with the same key is already queued so the 4th client takes its place. (queue: 0cf1=4th)

A 5th player connecting with a different browser should get its own session and be placed second when joining the queue.

**Comment by ecryth** [comment] 2014-05-06 14:46
Why are current players handled differently from queued players? At the second step, why is the second client able to become player 2? This behaviour is confusing.

**Comment by Zetro** [comment] 2014-05-06 14:50
Players leave the queue and can't be controlled by the queue anymore and the queue have no way of knowing if a session is currently playing

Edit: Duplicate clients being kicked is intended but players being able to join from a different tab isn't.

**Comment by ecryth** [comment] 2014-05-06 15:10
It's still confusing to a user that opening multiple tabs triggers different behaviour depending on whether they're queued or already playing. Why doesn't the queue keep track of playing users?

**Comment by Zetro** [comment] 2014-05-06 15:15
I don't know but the queue is quite simplistic and never communicate with games except the one-way pop call from games

**Comment by ecryth** [comment] 2014-05-06 17:14
I think it's worth generalizing the queue's behaviour so that the current players are always the two players at the front of the queue. The game could tell the queue how many simultaneous players it supports (generally 2 for the time being), and the queue would then inform the game whenever there are enough players in the queue to start a game, and tell the game to pause if there are to few players to keep the game going. The game wouldn't have to keep track of individual clients, instead just keeping track of whether it's player 1's or player 2's turn; the queue would do the actual work of keeping track of who those players are exactly, and making sure that new users are brought in to fill the place of a player that has dropped out.

But I guess that this issue (#92) should really be closed in favour of a new one more explicitly outlining the problems I've described here?

**Comment by Zetro** [comment] 2014-05-14 15:03
Fixed in ffe8fa68892644f364a4803cb3833d2fec116276

**Closed as completed by Zetro** 2014-05-14 15:03 UTC
Labels: bug, games, Low priority
