### ISSUE TITLE
[games] "Invalid moves" in connect4 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#70] opened 2014-04-07 10:43 UTC
Start a game and join it with two clients. Make some moves and then make som changes in the repository, so that the webserver restarts (debugmode). Then refresh the clients and have them join again. Several moves are now invalid. 

(I think this is how you recreate it)

**Comment by FireyFly** [comment] 2014-04-13 21:19
I can't reproduce this. I set the game to Connect4, have two clients open the game and join, make a few moves, and then save a python file forcing a Tornado restart. Then, the two clients' inputs get no response¹ (because the web server they are connected to doesn't exist anymore). I then reload the two clients, and as expected a new Connect4 game has started and all moves (including those in lanes where earlier moves were done) seem to work correctly for me.

¹) Arguably the clients should get a "game destroyed" notification, but I don't think that's possible unless one could hook up to Tornado's debug restart thing... but is this really an issue, considering this mode is only used for, well, debugging?

**Comment by FireyFly** [comment] 2014-04-13 21:27
Closing as invalid and opening the other referenced issue instead, as it more accurately describes the problem.

**Closed as completed by FireyFly** 2014-04-13 21:27 UTC
Labels: bug, games
